# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  -
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}

    gcflags:
      - all=-trimpath={{.Env.GOPATH}}

    goos:
      - darwin
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x

    env:
      - CGO_ENABLED=0

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
